#############################################################################
#   This is a configuration file for the provider-credential-server command.
#
#   COMMAND LINE ARGUMENTS AND ENVIRONMENT VARIABLES
#   ------------------------------------------------
#   Each configuration element can be overridden via command line
#   arguments or environment variables.  The precedence for determining
#   the value of each element is as follows:
#   1) command line argument
#      Examples:
#      a) --port 443
#         To set the listening port
#   2) environment variable
#      Examples:
#      a) CREDENTIAL_PROVIDER_SERVER_PORT=443
#         To set the listening port
#      b) CREDENTIAL_PROVIDER_SERVER_KEYFILE="../mykey.pem"
#         To set the "keyfile" element in the "ca" section below;
#         note the '_' separator character.
#   3) configuration file
#   4) default value (if there is one)
#      All default values are shown beside each element below.
#
#   FILE NAME ELEMENTS
#   ------------------
#   The value of all fields whose name ends with "file" or "files" are
#   name or names of other files.
#   For example, see "tls.certfile" and "tls.clientauth.certfiles".
#   The value of each of these fields can be a simple filename, a
#   relative path, or an absolute path.  If the value is not an
#   absolute path, it is interpretted as being relative to the location
#   of this configuration file.
#
#############################################################################

# Version of config file
version: 0.0.9

# Server's listening port (default: 8000)
port: 8000

# Enables debug logging (default: false)
debug: false

# Node Ethereum Blockchain
node: http://eth.everis.id

# Issuer
issuer: did:ev:12345

#############################################################################
#  Repository section
#  Supported types are: "smartContract".
#############################################################################
repository:
  type: smartContract
  address: REPO_ADDRESS

#############################################################################
#  Proof section
#  Supported types are: "SmartContract, P-256, Secp256k1".
#############################################################################
proof:
  type: SmartContract
  verification: 0x0f6487d9640f4230e09d0c2c0ef8b2bef6592573

#############################################################################
# BCCSP (BlockChain Crypto Service Provider) section is used to select which
# crypto library implementation to use
#############################################################################
bccsp:
  hash: SHA2
  security: 256
  # The directory used for the software file-based keystore
  keyStore: ./keystore/UTC--2019
