apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: provider-credential
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: provider-credential
    spec:
      containers:
        - name: provider-credential
          image: aparejaa/credentialprovider:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
#      imagePullSecrets:
#        - name: registry.gitlab.com
---
apiVersion: v1
kind: Service
metadata:
  name: provider-credential
  labels:
    app: provider-credential
spec:
  ports:
    - name: http
      targetPort: 8000
      protocol: TCP
      port: 8000
  selector:
    app: provider-credential
