// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Credential Provider
This is a Provider Credential Server that validates, signs, generates, revokes and updates credential to identify persons, institutions and objects.

The Provider Credential Server sign a credential using its own keys, it is configurable.

The Provider Credential needs to manage its own repository of credentials, default is smart contract that is deployed when server init.

The Credentials are verifiable against blockchain default, but you can configure and choose your proof and revocation list service.

Terms Of Service:

http://swagger.io/terms/


    Schemes:
      http
      https
    Host: localhost:8000
    BasePath: /v1
    Version: 0.0.1
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: <aparejaa@everis.com>

    Consumes:
    - application/json
    - application/xml

    Produces:
    - application/json
    - application/xml

swagger:meta
*/
package restapi
