// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a Provider Credential Server that validates, signs, generates, revokes and updates credential to identify persons, institutions and objects.\n\nThe Provider Credential Server sign a credential using its own keys, it is configurable.\n\nThe Provider Credential needs to manage its own repository of credentials, default is smart contract that is deployed when server init.\n\nThe Credentials are verifiable against blockchain default, but you can configure and choose your proof and revocation list service.",
    "title": "Credential Provider",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "email": "aparejaa@everis.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "0.0.1"
  },
  "host": "localhost:8000",
  "basePath": "/v1",
  "paths": {
    "/credential": {
      "post": {
        "description": "This service is responsible for generating verifiable credentials, storing the credential hash in the blockchain. You send the credential data with type of credential, range of valid dates and evidence generated about credential as optional",
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "produces": [
          "application/xml",
          "application/json"
        ],
        "tags": [
          "credential"
        ],
        "summary": "Create Credential",
        "operationId": "createCredential",
        "parameters": [
          {
            "description": "Created credential object",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/CredentialSubject"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Credential"
              }
            }
          },
          "400": {
            "description": "Invalid credential supplied",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/CredentialSubject"
              }
            }
          },
          "404": {
            "description": "DID not found"
          },
          "500": {
            "description": "Error Internal Server"
          }
        }
      }
    },
    "/credential/verify": {
      "post": {
        "description": "This service verify into blockchain if the credentials are current and these were not revoked",
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "produces": [
          "application/xml",
          "application/json"
        ],
        "tags": [
          "credential"
        ],
        "summary": "Verify a credential",
        "operationId": "verifyCredential",
        "parameters": [
          {
            "description": "the credentials that needs be validated.",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Credential"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/VerifyResponse"
            }
          },
          "400": {
            "description": "Invalid credential supplied"
          },
          "404": {
            "description": "DID not found"
          },
          "500": {
            "description": "Error Internal Server"
          }
        }
      }
    },
    "/credential/{credentialId}": {
      "get": {
        "description": "This service returns a credential verifiable",
        "produces": [
          "application/xml",
          "application/json"
        ],
        "tags": [
          "credential"
        ],
        "summary": "Get a Credential by ID",
        "operationId": "getCredentialById",
        "parameters": [
          {
            "type": "string",
            "description": "the credential id that needs be returned.",
            "name": "credentialId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Credential"
            }
          },
          "400": {
            "description": "Invalid credential Id supplied"
          },
          "404": {
            "description": "ID not found"
          },
          "500": {
            "description": "Error Internal Server"
          }
        }
      },
      "put": {
        "description": "This service updates a verifiable credential. First revoke the old credential with credential id, after generates a new credential with updated data from credential subject",
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "produces": [
          "application/xml",
          "application/json"
        ],
        "tags": [
          "credential"
        ],
        "summary": "Renewal a credential",
        "operationId": "renewalCredential",
        "parameters": [
          {
            "type": "string",
            "description": "Credential ID to update credential",
            "name": "credentialId",
            "in": "path",
            "required": true
          },
          {
            "description": "The data credential that needs be updated.",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CredentialSubject"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Credential"
            }
          },
          "400": {
            "description": "Invalid credential supplied"
          },
          "404": {
            "description": "Credential ID not found"
          },
          "500": {
            "description": "Error Internal Server"
          }
        }
      },
      "delete": {
        "description": "This service revokes a credential in the credential revocation list(Blockchain) providing a credential Id",
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "produces": [
          "application/xml",
          "application/json"
        ],
        "tags": [
          "credential"
        ],
        "summary": "Revoke a credential",
        "operationId": "revokeCredential",
        "parameters": [
          {
            "type": "string",
            "description": "Credential ID to revoke",
            "name": "credentialId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation"
          },
          "400": {
            "description": "Invalid ID credential supplied"
          },
          "404": {
            "description": "credential not found"
          },
          "500": {
            "description": "Error Internal Server"
          }
        }
      }
    },
    "/did/{did}": {
      "get": {
        "description": "This service validates through JWT if a DID is valid. The JWT contains a did of a person, institution or object that needs be validated. The owner of did sign the payload with its private key",
        "produces": [
          "application/xml",
          "application/json"
        ],
        "tags": [
          "did"
        ],
        "summary": "Validate a DID",
        "operationId": "validateDid",
        "parameters": [
          {
            "type": "string",
            "description": "The did that needs be validated. Use JWT. Example: eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiJkaWQ6ZXY6MnVpMVhQUmthOEV4d21GOG9KaFE2cVpicXMxWEdBUTJ5dUYiLCJpc3MiOiJmYWQ2Mjg0OGYxYTZjZGU0YzRkOTQ1M2RhZGVhNzE0Y2JkNTlmMTI4MjA4Nzg1M2RlOGIwYzYwNzJiZWMyN2U3YzZkOTExOWViMTY5YjQ0NDAzZTgzYjVlODdmOThjNzJiMDFjMmQ0NjQyMDA2YjE1NDZiMDA0MGFhNGUwNTU0ZiIsImlhdCI6MTU0OTMwNzMzMCwiZXhwIjoxNTQ5NDg3MzMwfQ.f2PJRQeb4BY-LiRZm_DnJw1aS2Anu5AAav6Wuq6ZbddgvMFg35tEbTm2vCVlRN-sjQ_Ffsce3ZfrBS2tqlSM9w",
            "name": "did",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation"
          },
          "400": {
            "description": "Invalid did supplied"
          },
          "404": {
            "description": "DID not found"
          },
          "500": {
            "description": "Error Internal Server"
          }
        }
      }
    }
  },
  "definitions": {
    "Credential": {
      "type": "object",
      "required": [
        "id",
        "type",
        "credentialSubject",
        "proof"
      ],
      "properties": {
        "credentialSubject": {
          "description": "The claims about a DID or identity that will be signed by Credential Provider"
        },
        "evidence": {
          "description": "The evidence obtained from the validation of the claims, may be photos, physical documents, links, etc"
        },
        "id": {
          "description": "The credential ID generated by the Provider Credential",
          "type": "string"
        },
        "issuanceDate": {
          "description": "credential issuance date",
          "type": "string",
          "format": "date-time"
        },
        "issuer": {
          "description": "The DID or identity of Provider Credential",
          "type": "string"
        },
        "proof": {
          "$ref": "#/definitions/Proof"
        },
        "type": {
          "description": "The types of this credential",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "xml": {
        "name": "Credential"
      },
      "example": {
        "credentialSubject": {
          "birthDate": "1990-01-01",
          "lastname": "Perez",
          "name": "Jose"
        },
        "evidence": {
          "face": "W8duzeDnC9h9Ksx2UtndRT6dIY9zHoSSB1/L2oMmrs//7k=",
          "photoBackDNI": "DnC9h9Ksx2UtndRxAhoTyxPPGM/rWfcW8dunC9h9Ksx2UtndRxAhoTyxPPGM/rWfcW8duzT6dIY9zHoSSB1/L2oMmrs/w4l=",
          "photoFrontDNI": "3c9f6UAYaIJsXUJDIM7lb2+tTW1ukkhnhwzDnC9h9Ksx2UtndRxAhoTyxPPGM/rWfcW8duzT6dIY9zHoSSB1/L2oMmrs//9k="
        },
        "expirationDate": "2020-01-01T19:23:24Z",
        "id": "http://example.edu/credentials/3732",
        "issuanceDate": "2010-01-01T19:23:24Z",
        "issuer": "did:ev:MIN12345",
        "proof": {
          "created": "2018-06-18T21:19:10Z",
          "signatureValue": "BavEll0/I1zpYw8XNi1bgVg/sCneO4Jugez8RwDg/+MCRVpjOboDoe4SxxKjkCOvKiCHGDvc4krqi6Z1n0UfqzxGfmatCuFibcC1wpsPRdW+gGsutPTLzvueMWmFhwYmfIFpbBu95t501+rSLHIEuujM/+PXr9Cky6Ed+W3JT24=",
          "type": "Secp256k1",
          "verificationMethod": "a12345df12ba123abcdf1298765f"
        },
        "type": [
          "VerifiableCredential",
          "UniversityDegreeCredential"
        ]
      }
    },
    "CredentialSubject": {
      "type": "object",
      "properties": {
        "content": {
          "description": "The claims that will be generated with the credential"
        },
        "evidence": {
          "description": "The evidence obtained from the validation of the claims, may be photos, physical documents, links, etc"
        },
        "expirationDate": {
          "description": "credential expiration date",
          "type": "string",
          "format": "date-time"
        },
        "issuanceDate": {
          "description": "credential issuance date",
          "type": "string",
          "format": "date-time"
        },
        "type": {
          "description": "Credential Type",
          "type": "string"
        }
      },
      "example": {
        "content": {
          "birthDate": "1990-01-01",
          "lastname": "Perez",
          "name": "Jose"
        },
        "evidence": {
          "face": "W8duzeDnC9h9Ksx2UtndRT6dIY9zHoSSB1/L2oMmrs//7k=",
          "photoBackDNI": "DnC9h9Ksx2UtndRxAhoTyxPPGM/rWfcW8dunC9h9Ksx2UtndRxAhoTyxPPGM/rWfcW8duzT6dIY9zHoSSB1/L2oMmrs/w4l=",
          "photoFrontDNI": "3c9f6UAYaIJsXUJDIM7lb2+tTW1ukkhnhwzDnC9h9Ksx2UtndRxAhoTyxPPGM/rWfcW8duzT6dIY9zHoSSB1/L2oMmrs//9k="
        },
        "expirationDate": "2022-01-01T19:23:24Z",
        "issuanceDate": "2019-01-01T19:23:24Z",
        "type": "DNI"
      }
    },
    "Error": {
      "type": "object",
      "properties": {
        "code": {
          "description": "Internal error code",
          "type": "string"
        },
        "message": {
          "description": "Internal error message",
          "type": "string"
        }
      }
    },
    "Proof": {
      "type": "object",
      "properties": {
        "created": {
          "description": "The date of the digital signature with format YYYY-MM-DDTHH:MM:SSZ",
          "type": "string",
          "format": "date-time"
        },
        "signatureValue": {
          "description": "the digital signature of credential provider",
          "type": "string"
        },
        "type": {
          "description": "Sign Algorithm",
          "type": "string",
          "enum": [
            "SmartContract",
            "RSASignature",
            "Secp256k1",
            "Secp256r1"
          ]
        },
        "verificationMethod": {
          "description": "The method to proof if a credential is valid. The methods can include smart contracts, public keys",
          "type": "string"
        }
      },
      "xml": {
        "name": "Proof"
      }
    },
    "VerifyResponse": {
      "type": "object",
      "properties": {
        "error": {
          "description": "Error code and message ocurred",
          "$ref": "#/definitions/Proof"
        },
        "valid": {
          "description": "Credentials are validated",
          "type": "boolean"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Operations about credential",
      "name": "credential",
      "externalDocs": {
        "description": "Find out more about verifiable credential",
        "url": "https://w3c.github.io/vc-data-model/"
      }
    },
    {
      "description": "Operations about DID",
      "name": "did",
      "externalDocs": {
        "description": "Find out more about DIDs",
        "url": "https://w3c-ccg.github.io/did-spec/"
      }
    }
  ],
  "externalDocs": {
    "description": "Find out more about Swagger",
    "url": "http://swagger.io"
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a Provider Credential Server that validates, signs, generates, revokes and updates credential to identify persons, institutions and objects.\n\nThe Provider Credential Server sign a credential using its own keys, it is configurable.\n\nThe Provider Credential needs to manage its own repository of credentials, default is smart contract that is deployed when server init.\n\nThe Credentials are verifiable against blockchain default, but you can configure and choose your proof and revocation list service.",
    "title": "Credential Provider",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "email": "aparejaa@everis.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "0.0.1"
  },
  "host": "localhost:8000",
  "basePath": "/v1",
  "paths": {
    "/credential": {
      "post": {
        "description": "This service is responsible for generating verifiable credentials, storing the credential hash in the blockchain. You send the credential data with type of credential, range of valid dates and evidence generated about credential as optional",
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "produces": [
          "application/xml",
          "application/json"
        ],
        "tags": [
          "credential"
        ],
        "summary": "Create Credential",
        "operationId": "createCredential",
        "parameters": [
          {
            "description": "Created credential object",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/CredentialSubject"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Credential"
              }
            }
          },
          "400": {
            "description": "Invalid credential supplied",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/CredentialSubject"
              }
            }
          },
          "404": {
            "description": "DID not found"
          },
          "500": {
            "description": "Error Internal Server"
          }
        }
      }
    },
    "/credential/verify": {
      "post": {
        "description": "This service verify into blockchain if the credentials are current and these were not revoked",
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "produces": [
          "application/xml",
          "application/json"
        ],
        "tags": [
          "credential"
        ],
        "summary": "Verify a credential",
        "operationId": "verifyCredential",
        "parameters": [
          {
            "description": "the credentials that needs be validated.",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Credential"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/VerifyResponse"
            }
          },
          "400": {
            "description": "Invalid credential supplied"
          },
          "404": {
            "description": "DID not found"
          },
          "500": {
            "description": "Error Internal Server"
          }
        }
      }
    },
    "/credential/{credentialId}": {
      "get": {
        "description": "This service returns a credential verifiable",
        "produces": [
          "application/xml",
          "application/json"
        ],
        "tags": [
          "credential"
        ],
        "summary": "Get a Credential by ID",
        "operationId": "getCredentialById",
        "parameters": [
          {
            "type": "string",
            "description": "the credential id that needs be returned.",
            "name": "credentialId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Credential"
            }
          },
          "400": {
            "description": "Invalid credential Id supplied"
          },
          "404": {
            "description": "ID not found"
          },
          "500": {
            "description": "Error Internal Server"
          }
        }
      },
      "put": {
        "description": "This service updates a verifiable credential. First revoke the old credential with credential id, after generates a new credential with updated data from credential subject",
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "produces": [
          "application/xml",
          "application/json"
        ],
        "tags": [
          "credential"
        ],
        "summary": "Renewal a credential",
        "operationId": "renewalCredential",
        "parameters": [
          {
            "type": "string",
            "description": "Credential ID to update credential",
            "name": "credentialId",
            "in": "path",
            "required": true
          },
          {
            "description": "The data credential that needs be updated.",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CredentialSubject"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Credential"
            }
          },
          "400": {
            "description": "Invalid credential supplied"
          },
          "404": {
            "description": "Credential ID not found"
          },
          "500": {
            "description": "Error Internal Server"
          }
        }
      },
      "delete": {
        "description": "This service revokes a credential in the credential revocation list(Blockchain) providing a credential Id",
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "produces": [
          "application/xml",
          "application/json"
        ],
        "tags": [
          "credential"
        ],
        "summary": "Revoke a credential",
        "operationId": "revokeCredential",
        "parameters": [
          {
            "type": "string",
            "description": "Credential ID to revoke",
            "name": "credentialId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation"
          },
          "400": {
            "description": "Invalid ID credential supplied"
          },
          "404": {
            "description": "credential not found"
          },
          "500": {
            "description": "Error Internal Server"
          }
        }
      }
    },
    "/did/{did}": {
      "get": {
        "description": "This service validates through JWT if a DID is valid. The JWT contains a did of a person, institution or object that needs be validated. The owner of did sign the payload with its private key",
        "produces": [
          "application/xml",
          "application/json"
        ],
        "tags": [
          "did"
        ],
        "summary": "Validate a DID",
        "operationId": "validateDid",
        "parameters": [
          {
            "type": "string",
            "description": "The did that needs be validated. Use JWT. Example: eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiJkaWQ6ZXY6MnVpMVhQUmthOEV4d21GOG9KaFE2cVpicXMxWEdBUTJ5dUYiLCJpc3MiOiJmYWQ2Mjg0OGYxYTZjZGU0YzRkOTQ1M2RhZGVhNzE0Y2JkNTlmMTI4MjA4Nzg1M2RlOGIwYzYwNzJiZWMyN2U3YzZkOTExOWViMTY5YjQ0NDAzZTgzYjVlODdmOThjNzJiMDFjMmQ0NjQyMDA2YjE1NDZiMDA0MGFhNGUwNTU0ZiIsImlhdCI6MTU0OTMwNzMzMCwiZXhwIjoxNTQ5NDg3MzMwfQ.f2PJRQeb4BY-LiRZm_DnJw1aS2Anu5AAav6Wuq6ZbddgvMFg35tEbTm2vCVlRN-sjQ_Ffsce3ZfrBS2tqlSM9w",
            "name": "did",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation"
          },
          "400": {
            "description": "Invalid did supplied"
          },
          "404": {
            "description": "DID not found"
          },
          "500": {
            "description": "Error Internal Server"
          }
        }
      }
    }
  },
  "definitions": {
    "Credential": {
      "type": "object",
      "required": [
        "id",
        "type",
        "credentialSubject",
        "proof"
      ],
      "properties": {
        "credentialSubject": {
          "description": "The claims about a DID or identity that will be signed by Credential Provider"
        },
        "evidence": {
          "description": "The evidence obtained from the validation of the claims, may be photos, physical documents, links, etc"
        },
        "id": {
          "description": "The credential ID generated by the Provider Credential",
          "type": "string"
        },
        "issuanceDate": {
          "description": "credential issuance date",
          "type": "string",
          "format": "date-time"
        },
        "issuer": {
          "description": "The DID or identity of Provider Credential",
          "type": "string"
        },
        "proof": {
          "$ref": "#/definitions/Proof"
        },
        "type": {
          "description": "The types of this credential",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "xml": {
        "name": "Credential"
      },
      "example": {
        "credentialSubject": {
          "birthDate": "1990-01-01",
          "lastname": "Perez",
          "name": "Jose"
        },
        "evidence": {
          "face": "W8duzeDnC9h9Ksx2UtndRT6dIY9zHoSSB1/L2oMmrs//7k=",
          "photoBackDNI": "DnC9h9Ksx2UtndRxAhoTyxPPGM/rWfcW8dunC9h9Ksx2UtndRxAhoTyxPPGM/rWfcW8duzT6dIY9zHoSSB1/L2oMmrs/w4l=",
          "photoFrontDNI": "3c9f6UAYaIJsXUJDIM7lb2+tTW1ukkhnhwzDnC9h9Ksx2UtndRxAhoTyxPPGM/rWfcW8duzT6dIY9zHoSSB1/L2oMmrs//9k="
        },
        "expirationDate": "2020-01-01T19:23:24Z",
        "id": "http://example.edu/credentials/3732",
        "issuanceDate": "2010-01-01T19:23:24Z",
        "issuer": "did:ev:MIN12345",
        "proof": {
          "created": "2018-06-18T21:19:10Z",
          "signatureValue": "BavEll0/I1zpYw8XNi1bgVg/sCneO4Jugez8RwDg/+MCRVpjOboDoe4SxxKjkCOvKiCHGDvc4krqi6Z1n0UfqzxGfmatCuFibcC1wpsPRdW+gGsutPTLzvueMWmFhwYmfIFpbBu95t501+rSLHIEuujM/+PXr9Cky6Ed+W3JT24=",
          "type": "Secp256k1",
          "verificationMethod": "a12345df12ba123abcdf1298765f"
        },
        "type": [
          "VerifiableCredential",
          "UniversityDegreeCredential"
        ]
      }
    },
    "CredentialSubject": {
      "type": "object",
      "properties": {
        "content": {
          "description": "The claims that will be generated with the credential"
        },
        "evidence": {
          "description": "The evidence obtained from the validation of the claims, may be photos, physical documents, links, etc"
        },
        "expirationDate": {
          "description": "credential expiration date",
          "type": "string",
          "format": "date-time"
        },
        "issuanceDate": {
          "description": "credential issuance date",
          "type": "string",
          "format": "date-time"
        },
        "type": {
          "description": "Credential Type",
          "type": "string"
        }
      },
      "example": {
        "content": {
          "birthDate": "1990-01-01",
          "lastname": "Perez",
          "name": "Jose"
        },
        "evidence": {
          "face": "W8duzeDnC9h9Ksx2UtndRT6dIY9zHoSSB1/L2oMmrs//7k=",
          "photoBackDNI": "DnC9h9Ksx2UtndRxAhoTyxPPGM/rWfcW8dunC9h9Ksx2UtndRxAhoTyxPPGM/rWfcW8duzT6dIY9zHoSSB1/L2oMmrs/w4l=",
          "photoFrontDNI": "3c9f6UAYaIJsXUJDIM7lb2+tTW1ukkhnhwzDnC9h9Ksx2UtndRxAhoTyxPPGM/rWfcW8duzT6dIY9zHoSSB1/L2oMmrs//9k="
        },
        "expirationDate": "2022-01-01T19:23:24Z",
        "issuanceDate": "2019-01-01T19:23:24Z",
        "type": "DNI"
      }
    },
    "Error": {
      "type": "object",
      "properties": {
        "code": {
          "description": "Internal error code",
          "type": "string"
        },
        "message": {
          "description": "Internal error message",
          "type": "string"
        }
      }
    },
    "Proof": {
      "type": "object",
      "properties": {
        "created": {
          "description": "The date of the digital signature with format YYYY-MM-DDTHH:MM:SSZ",
          "type": "string",
          "format": "date-time"
        },
        "signatureValue": {
          "description": "the digital signature of credential provider",
          "type": "string"
        },
        "type": {
          "description": "Sign Algorithm",
          "type": "string",
          "enum": [
            "SmartContract",
            "RSASignature",
            "Secp256k1",
            "Secp256r1"
          ]
        },
        "verificationMethod": {
          "description": "The method to proof if a credential is valid. The methods can include smart contracts, public keys",
          "type": "string"
        }
      },
      "xml": {
        "name": "Proof"
      }
    },
    "VerifyResponse": {
      "type": "object",
      "properties": {
        "error": {
          "description": "Error code and message ocurred",
          "$ref": "#/definitions/Error"
        },
        "valid": {
          "description": "Credentials are validated",
          "type": "boolean"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Operations about credential",
      "name": "credential",
      "externalDocs": {
        "description": "Find out more about verifiable credential",
        "url": "https://w3c.github.io/vc-data-model/"
      }
    },
    {
      "description": "Operations about DID",
      "name": "did",
      "externalDocs": {
        "description": "Find out more about DIDs",
        "url": "https://w3c-ccg.github.io/did-spec/"
      }
    }
  ],
  "externalDocs": {
    "description": "Find out more about Swagger",
    "url": "http://swagger.io"
  }
}`))
}
