// Code generated by go-swagger; DO NOT EDIT.

package did

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ValidateDidOKCode is the HTTP code returned for type ValidateDidOK
const ValidateDidOKCode int = 200

/*ValidateDidOK successful operation

swagger:response validateDidOK
*/
type ValidateDidOK struct {
}

// NewValidateDidOK creates ValidateDidOK with default headers values
func NewValidateDidOK() *ValidateDidOK {

	return &ValidateDidOK{}
}

// WriteResponse to the client
func (o *ValidateDidOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// ValidateDidBadRequestCode is the HTTP code returned for type ValidateDidBadRequest
const ValidateDidBadRequestCode int = 400

/*ValidateDidBadRequest Invalid did supplied

swagger:response validateDidBadRequest
*/
type ValidateDidBadRequest struct {
}

// NewValidateDidBadRequest creates ValidateDidBadRequest with default headers values
func NewValidateDidBadRequest() *ValidateDidBadRequest {

	return &ValidateDidBadRequest{}
}

// WriteResponse to the client
func (o *ValidateDidBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// ValidateDidNotFoundCode is the HTTP code returned for type ValidateDidNotFound
const ValidateDidNotFoundCode int = 404

/*ValidateDidNotFound DID not found

swagger:response validateDidNotFound
*/
type ValidateDidNotFound struct {
}

// NewValidateDidNotFound creates ValidateDidNotFound with default headers values
func NewValidateDidNotFound() *ValidateDidNotFound {

	return &ValidateDidNotFound{}
}

// WriteResponse to the client
func (o *ValidateDidNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// ValidateDidInternalServerErrorCode is the HTTP code returned for type ValidateDidInternalServerError
const ValidateDidInternalServerErrorCode int = 500

/*ValidateDidInternalServerError Error Internal Server

swagger:response validateDidInternalServerError
*/
type ValidateDidInternalServerError struct {
}

// NewValidateDidInternalServerError creates ValidateDidInternalServerError with default headers values
func NewValidateDidInternalServerError() *ValidateDidInternalServerError {

	return &ValidateDidInternalServerError{}
}

// WriteResponse to the client
func (o *ValidateDidInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
