// Code generated by go-swagger; DO NOT EDIT.

package credential

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "github.com/ccamaleon5/CredentialMother/models"
)

// NewCreateCredentialParams creates a new CreateCredentialParams object
// no default values defined in spec.
func NewCreateCredentialParams() CreateCredentialParams {

	return CreateCredentialParams{}
}

// CreateCredentialParams contains all the bound params for the create credential operation
// typically these are obtained from a http.Request
//
// swagger:parameters createCredential
type CreateCredentialParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Created credential object
	  Required: true
	  In: body
	*/
	Body []*models.CredentialSubject
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateCredentialParams() beforehand.
func (o *CreateCredentialParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body []*models.CredentialSubject
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate array of body objects
			for i := range body {
				if body[i] == nil {
					continue
				}
				if err := body[i].Validate(route.Formats); err != nil {
					res = append(res, err)
					break
				}
			}
			if len(res) == 0 {
				o.Body = body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
