// Code generated by go-swagger; DO NOT EDIT.

package credential

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/ccamaleon5/CredentialMother/models"
)

// GetCredentialByIDOKCode is the HTTP code returned for type GetCredentialByIDOK
const GetCredentialByIDOKCode int = 200

/*GetCredentialByIDOK successful operation

swagger:response getCredentialByIdOK
*/
type GetCredentialByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Credential `json:"body,omitempty"`
}

// NewGetCredentialByIDOK creates GetCredentialByIDOK with default headers values
func NewGetCredentialByIDOK() *GetCredentialByIDOK {

	return &GetCredentialByIDOK{}
}

// WithPayload adds the payload to the get credential by Id o k response
func (o *GetCredentialByIDOK) WithPayload(payload *models.Credential) *GetCredentialByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get credential by Id o k response
func (o *GetCredentialByIDOK) SetPayload(payload *models.Credential) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCredentialByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCredentialByIDBadRequestCode is the HTTP code returned for type GetCredentialByIDBadRequest
const GetCredentialByIDBadRequestCode int = 400

/*GetCredentialByIDBadRequest Invalid credential Id supplied

swagger:response getCredentialByIdBadRequest
*/
type GetCredentialByIDBadRequest struct {
}

// NewGetCredentialByIDBadRequest creates GetCredentialByIDBadRequest with default headers values
func NewGetCredentialByIDBadRequest() *GetCredentialByIDBadRequest {

	return &GetCredentialByIDBadRequest{}
}

// WriteResponse to the client
func (o *GetCredentialByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetCredentialByIDNotFoundCode is the HTTP code returned for type GetCredentialByIDNotFound
const GetCredentialByIDNotFoundCode int = 404

/*GetCredentialByIDNotFound ID not found

swagger:response getCredentialByIdNotFound
*/
type GetCredentialByIDNotFound struct {
}

// NewGetCredentialByIDNotFound creates GetCredentialByIDNotFound with default headers values
func NewGetCredentialByIDNotFound() *GetCredentialByIDNotFound {

	return &GetCredentialByIDNotFound{}
}

// WriteResponse to the client
func (o *GetCredentialByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetCredentialByIDInternalServerErrorCode is the HTTP code returned for type GetCredentialByIDInternalServerError
const GetCredentialByIDInternalServerErrorCode int = 500

/*GetCredentialByIDInternalServerError Error Internal Server

swagger:response getCredentialByIdInternalServerError
*/
type GetCredentialByIDInternalServerError struct {
}

// NewGetCredentialByIDInternalServerError creates GetCredentialByIDInternalServerError with default headers values
func NewGetCredentialByIDInternalServerError() *GetCredentialByIDInternalServerError {

	return &GetCredentialByIDInternalServerError{}
}

// WriteResponse to the client
func (o *GetCredentialByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
