// Code generated by go-swagger; DO NOT EDIT.

package credential

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCredentialByIDParams creates a new GetCredentialByIDParams object
// no default values defined in spec.
func NewGetCredentialByIDParams() GetCredentialByIDParams {

	return GetCredentialByIDParams{}
}

// GetCredentialByIDParams contains all the bound params for the get credential by Id operation
// typically these are obtained from a http.Request
//
// swagger:parameters getCredentialById
type GetCredentialByIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*the credential id that needs be returned.
	  Required: true
	  In: path
	*/
	CredentialID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetCredentialByIDParams() beforehand.
func (o *GetCredentialByIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rCredentialID, rhkCredentialID, _ := route.Params.GetOK("credentialId")
	if err := o.bindCredentialID(rCredentialID, rhkCredentialID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCredentialID binds and validates parameter CredentialID from path.
func (o *GetCredentialByIDParams) bindCredentialID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.CredentialID = raw

	return nil
}
