// Code generated by go-swagger; DO NOT EDIT.

package credential

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ccamaleon5/CredentialMother/models"
)

// NewRenewalCredentialParams creates a new RenewalCredentialParams object
// no default values defined in spec.
func NewRenewalCredentialParams() RenewalCredentialParams {

	return RenewalCredentialParams{}
}

// RenewalCredentialParams contains all the bound params for the renewal credential operation
// typically these are obtained from a http.Request
//
// swagger:parameters renewalCredential
type RenewalCredentialParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The data credential that needs be updated.
	  Required: true
	  In: body
	*/
	Body *models.CredentialSubject
	/*Credential ID to update credential
	  Required: true
	  In: path
	*/
	CredentialID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewRenewalCredentialParams() beforehand.
func (o *RenewalCredentialParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.CredentialSubject
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body"))
	}
	rCredentialID, rhkCredentialID, _ := route.Params.GetOK("credentialId")
	if err := o.bindCredentialID(rCredentialID, rhkCredentialID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCredentialID binds and validates parameter CredentialID from path.
func (o *RenewalCredentialParams) bindCredentialID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.CredentialID = raw

	return nil
}
