// Code generated by go-swagger; DO NOT EDIT.

package credential

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RevokeCredentialOKCode is the HTTP code returned for type RevokeCredentialOK
const RevokeCredentialOKCode int = 200

/*RevokeCredentialOK successful operation

swagger:response revokeCredentialOK
*/
type RevokeCredentialOK struct {
}

// NewRevokeCredentialOK creates RevokeCredentialOK with default headers values
func NewRevokeCredentialOK() *RevokeCredentialOK {

	return &RevokeCredentialOK{}
}

// WriteResponse to the client
func (o *RevokeCredentialOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// RevokeCredentialBadRequestCode is the HTTP code returned for type RevokeCredentialBadRequest
const RevokeCredentialBadRequestCode int = 400

/*RevokeCredentialBadRequest Invalid ID credential supplied

swagger:response revokeCredentialBadRequest
*/
type RevokeCredentialBadRequest struct {
}

// NewRevokeCredentialBadRequest creates RevokeCredentialBadRequest with default headers values
func NewRevokeCredentialBadRequest() *RevokeCredentialBadRequest {

	return &RevokeCredentialBadRequest{}
}

// WriteResponse to the client
func (o *RevokeCredentialBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// RevokeCredentialNotFoundCode is the HTTP code returned for type RevokeCredentialNotFound
const RevokeCredentialNotFoundCode int = 404

/*RevokeCredentialNotFound credential not found

swagger:response revokeCredentialNotFound
*/
type RevokeCredentialNotFound struct {
}

// NewRevokeCredentialNotFound creates RevokeCredentialNotFound with default headers values
func NewRevokeCredentialNotFound() *RevokeCredentialNotFound {

	return &RevokeCredentialNotFound{}
}

// WriteResponse to the client
func (o *RevokeCredentialNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// RevokeCredentialInternalServerErrorCode is the HTTP code returned for type RevokeCredentialInternalServerError
const RevokeCredentialInternalServerErrorCode int = 500

/*RevokeCredentialInternalServerError Error Internal Server

swagger:response revokeCredentialInternalServerError
*/
type RevokeCredentialInternalServerError struct {
}

// NewRevokeCredentialInternalServerError creates RevokeCredentialInternalServerError with default headers values
func NewRevokeCredentialInternalServerError() *RevokeCredentialInternalServerError {

	return &RevokeCredentialInternalServerError{}
}

// WriteResponse to the client
func (o *RevokeCredentialInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
