// Code generated by go-swagger; DO NOT EDIT.

package credential

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/ccamaleon5/CredentialMother/models"
)

// VerifyCredentialOKCode is the HTTP code returned for type VerifyCredentialOK
const VerifyCredentialOKCode int = 200

/*VerifyCredentialOK successful operation

swagger:response verifyCredentialOK
*/
type VerifyCredentialOK struct {

	/*
	  In: Body
	*/
	Payload *models.VerifyResponse `json:"body,omitempty"`
}

// NewVerifyCredentialOK creates VerifyCredentialOK with default headers values
func NewVerifyCredentialOK() *VerifyCredentialOK {

	return &VerifyCredentialOK{}
}

// WithPayload adds the payload to the verify credential o k response
func (o *VerifyCredentialOK) WithPayload(payload *models.VerifyResponse) *VerifyCredentialOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the verify credential o k response
func (o *VerifyCredentialOK) SetPayload(payload *models.VerifyResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VerifyCredentialOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// VerifyCredentialBadRequestCode is the HTTP code returned for type VerifyCredentialBadRequest
const VerifyCredentialBadRequestCode int = 400

/*VerifyCredentialBadRequest Invalid credential supplied

swagger:response verifyCredentialBadRequest
*/
type VerifyCredentialBadRequest struct {
}

// NewVerifyCredentialBadRequest creates VerifyCredentialBadRequest with default headers values
func NewVerifyCredentialBadRequest() *VerifyCredentialBadRequest {

	return &VerifyCredentialBadRequest{}
}

// WriteResponse to the client
func (o *VerifyCredentialBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// VerifyCredentialNotFoundCode is the HTTP code returned for type VerifyCredentialNotFound
const VerifyCredentialNotFoundCode int = 404

/*VerifyCredentialNotFound DID not found

swagger:response verifyCredentialNotFound
*/
type VerifyCredentialNotFound struct {
}

// NewVerifyCredentialNotFound creates VerifyCredentialNotFound with default headers values
func NewVerifyCredentialNotFound() *VerifyCredentialNotFound {

	return &VerifyCredentialNotFound{}
}

// WriteResponse to the client
func (o *VerifyCredentialNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// VerifyCredentialInternalServerErrorCode is the HTTP code returned for type VerifyCredentialInternalServerError
const VerifyCredentialInternalServerErrorCode int = 500

/*VerifyCredentialInternalServerError Error Internal Server

swagger:response verifyCredentialInternalServerError
*/
type VerifyCredentialInternalServerError struct {
}

// NewVerifyCredentialInternalServerError creates VerifyCredentialInternalServerError with default headers values
func NewVerifyCredentialInternalServerError() *VerifyCredentialInternalServerError {

	return &VerifyCredentialInternalServerError{}
}

// WriteResponse to the client
func (o *VerifyCredentialInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
