// Code generated by go-swagger; DO NOT EDIT.

package credential

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// VerifyCredentialHandlerFunc turns a function with the right signature into a verify credential handler
type VerifyCredentialHandlerFunc func(VerifyCredentialParams) middleware.Responder

// Handle executing the request and returning a response
func (fn VerifyCredentialHandlerFunc) Handle(params VerifyCredentialParams) middleware.Responder {
	return fn(params)
}

// VerifyCredentialHandler interface for that can handle valid verify credential params
type VerifyCredentialHandler interface {
	Handle(VerifyCredentialParams) middleware.Responder
}

// NewVerifyCredential creates a new http.Handler for the verify credential operation
func NewVerifyCredential(ctx *middleware.Context, handler VerifyCredentialHandler) *VerifyCredential {
	return &VerifyCredential{Context: ctx, Handler: handler}
}

/*VerifyCredential swagger:route POST /credential/verify credential verifyCredential

Verify a credential

This service verify into blockchain if the credentials are current and these were not revoked

*/
type VerifyCredential struct {
	Context *middleware.Context
	Handler VerifyCredentialHandler
}

func (o *VerifyCredential) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewVerifyCredentialParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
