// Code generated by go-swagger; DO NOT EDIT.

package credential

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// VerifyHashCredentialHandlerFunc turns a function with the right signature into a verify hash credential handler
type VerifyHashCredentialHandlerFunc func(VerifyHashCredentialParams) middleware.Responder

// Handle executing the request and returning a response
func (fn VerifyHashCredentialHandlerFunc) Handle(params VerifyHashCredentialParams) middleware.Responder {
	return fn(params)
}

// VerifyHashCredentialHandler interface for that can handle valid verify hash credential params
type VerifyHashCredentialHandler interface {
	Handle(VerifyHashCredentialParams) middleware.Responder
}

// NewVerifyHashCredential creates a new http.Handler for the verify hash credential operation
func NewVerifyHashCredential(ctx *middleware.Context, handler VerifyHashCredentialHandler) *VerifyHashCredential {
	return &VerifyHashCredential{Context: ctx, Handler: handler}
}

/*VerifyHashCredential swagger:route GET /credential/{credentialHash}/verify credential verifyHashCredential

Verify a Hash credential

This service verify into blockchain if the hash credential is current and this was not revoked

*/
type VerifyHashCredential struct {
	Context *middleware.Context
	Handler VerifyHashCredentialHandler
}

func (o *VerifyHashCredential) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewVerifyHashCredentialParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
