// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CredentialRenewal credential renewal
// swagger:model CredentialRenewal
type CredentialRenewal struct {

	// Credential ID
	ID string `json:"id,omitempty"`

	// new expiration date
	// Format: date-time
	NewExpirationDate strfmt.DateTime `json:"newExpirationDate,omitempty"`
}

// Validate validates this credential renewal
func (m *CredentialRenewal) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNewExpirationDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CredentialRenewal) validateNewExpirationDate(formats strfmt.Registry) error {

	if swag.IsZero(m.NewExpirationDate) { // not required
		return nil
	}

	if err := validate.FormatOf("newExpirationDate", "body", "date-time", m.NewExpirationDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CredentialRenewal) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CredentialRenewal) UnmarshalBinary(b []byte) error {
	var res CredentialRenewal
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
